main: me.JayMar921.Warps.Main
name: CustomWarps_by_JayMar921
version: 1.0.3
author: JayMar921
api-version: 1.21
website: https://www.youtube.com/c/jaymar921/

commands:
  warps:
    description: Shows Warps GUI
    usage: /warps
  warp:
    description: Configure Warps (only OP players can use this)
    usage: /warp {sub_commands}
    permission: CustomWarps.warp

permissions:
  CustomWarps.warp:
    description: Players with this permission can modify the custom warp plugin
    default: op